package com.medic.Produtos.model.parametro.estoque;

import com.medic.Produtos.config.persistence.UUIDAutoGenerated;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

import java.io.Serial;
import java.io.Serializable;
import java.time.Instant;
import java.util.UUID;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Table("vale_permanente_parametros")
public class ValePermanenteParametroModel implements Serializable, UUIDAutoGenerated {

    @Serial
    private static final long serialVersionUID = 1L;

    @Id
    private UUID id;

    @Column("id_empresa")
    private UUID idEmpresa;

    @Column("cod_vp")
    private int codVp;

    @Column("compor_subCd")
    private UUID comporSubCd;

    @Column("criado_por")
    private UUID criadoPor;

    @Column("atualizado_por")
    private UUID atualizadoPor;

    @CreatedDate
    @Column("criado_em")
    private Instant criadoEm;

    @Column("atualizado_em")
    private Instant atualizadoEm;

}
