package com.medic.Web.model.usuario;

import com.medic.Web.config.persistence.UUIDAutoGenerated;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

import java.io.Serial;
import java.io.Serializable;
import java.time.Instant;
import java.util.UUID;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "usuario")
public class UsuarioModel implements Serializable, UUIDAutoGenerated {

    @Serial
    private static final long serialVersionUID = 1L;

    @Id
    private UUID id;

    @Column("nome")
    private String nome;

    @Column("email")
    private String email;

    @Column("senha")
    private String senha;

    @Column("role")
    private Role role;

    @Column("ativo")
    private Boolean ativo;

    @Column("primeiro_acesso")
    private Boolean primeiroAcesso;

    @Column("criado_por")
    private UUID criadoPor;

    @Column("atualizado_por")
    private UUID atualizadoPor;

    @CreatedDate
    @Column("criado_em")
    private Instant criadoEm;

    @Column("atualizado_em")
    private Instant atualizadoEm;
}
