package com.medic.Produtos.model.empresa;

import com.medic.Produtos.config.persistence.UUIDAutoGenerated;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

import java.io.Serial;
import java.io.Serializable;
import java.time.Instant;
import java.util.UUID;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Table("empresa")
public class EmpresaModel implements Serializable, UUIDAutoGenerated {

    @Serial
    private static final long serialVersionUID = 1L;

    @Id
    private UUID id;

    @Column("descricao")
    private String descricao;

    @Column("viman")
    private Viman viman;

    @Column("codigo_empresa")
    private String codigoEmpresa;

    @Column("possui_estoque_interno")
    private boolean possuiEstoqueInterno;

    @Column("possui_estoque_segregado")
    private boolean possuiEstoqueSegregado;

    @Column("possui_vp")
    private boolean possuiVp;

    @Column("criado_por")
    private UUID criadoPor;

    @Column("atualizado_por")
    private UUID atualizadoPor;

    @CreatedDate
    @Column("criado_em")
    private Instant criadoEm;

    @Column("atualizado_em")
    private Instant atualizadoEm;
}
