package com.medic.Web.model.parametro.periodo;

import com.medic.Web.config.persistence.UUIDAutoGenerated;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

import java.io.Serial;
import java.io.Serializable;
import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Table("periodo")
public class PeriodoModel implements Serializable, UUIDAutoGenerated {

    @Serial
    private static final long serialVersionUID = 1L;

    @Id
    private UUID id;

    @Column("descricao")
    private PeriodoEnum descricao;

    @Column("data_inicial")
    private LocalDate dataInicial;

    @Column("data_final")
    private LocalDate dataFinal;

    @Column("data_inicial_viman")
    private String dataInicialViman;

    @Column("data_final_viman")
    private String dataFinalViman;

    @Column("atualizado_por")
    private UUID atualizadoPor;

    @LastModifiedDate
    @Column("atualizado_em")
    private Instant atualizadoEm;
}
