package com.medic.Produtos.config.persistence;

import org.jspecify.annotations.NonNull;
import org.reactivestreams.Publisher;
import org.springframework.data.r2dbc.mapping.event.BeforeConvertCallback;
import org.springframework.data.relational.core.sql.SqlIdentifier;
import org.springframework.stereotype.Component;
import reactor.core.publisher.Mono;

import java.util.UUID;

@Component
public class UUIDAutoGeneratedConfig implements BeforeConvertCallback<UUIDAutoGenerated> {

    @Override
    public @NonNull Publisher<UUIDAutoGenerated> onBeforeConvert(UUIDAutoGenerated entity, @NonNull SqlIdentifier table) {

        if (entity.getId() == null)
            entity.setId(UUID.randomUUID());

        return Mono.just(entity);
    }
}
