package com.medic.Produtos.model.necessidade;

import com.medic.Produtos.config.persistence.UUIDAutoGenerated;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

import java.io.Serial;
import java.io.Serializable;
import java.util.UUID;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Table("necessidade")
public class NecessidadeModel implements Serializable, UUIDAutoGenerated {

    @Serial
    private static final long serialVersionUID = 1L;

    @Id
    private UUID id;

    @Column("id_empresa_municipio")
    private UUID idEmpresaMunicipio;

    @Column("cod_produto")
    private String codProduto;

    @Column("estoque")
    private int estoque;

    @Column("demanda")
    private int demanda;

    @Column("necessidade")
    private int necessidade;
}
