package com.medic.Produtos.model.auth;

import com.medic.Produtos.config.persistence.UUIDAutoGenerated;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

import java.io.Serial;
import java.io.Serializable;
import java.time.Instant;
import java.util.UUID;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "password_reset_code")
public class PasswordResetCodeModel implements Serializable, UUIDAutoGenerated {

    @Serial
    private static final long serialVersionUID = 1L;

    @Id
    private UUID id;

    @Column("email")
    private String email;

    @Column("codigo")
    private String codigo;

    @Column("criado_em")
    private Instant criadoEm;

    @Column("expira_em")
    private Instant expiraEm;

    @Column("usado")
    private boolean usado;

    public void marcarComoUsado() {
        this.usado = true;
    }
}
