package com.medic.Produtos.model.parametro.taxa;

import com.medic.Produtos.config.persistence.UUIDAutoGenerated;
import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

import java.io.Serial;
import java.io.Serializable;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Table("taxa")
public class TaxaModel implements Serializable, UUIDAutoGenerated {

    @Serial
    private static final long serialVersionUID = 1L;

    @Id
    private UUID id;

    @Column("descricao")
    private TaxaEnum descricao;

    @Column("taxa")
    private BigDecimal taxa;

    @Column("atualizado_por")
    private UUID atualizadoPor;

    @LastModifiedDate
    @Column("atualizado_em")
    private Instant atualizadoEm;
}
