package com.medic.Web.config;

import com.medic.Web.config.auth.CorsConfig;
import com.medic.Web.config.auth.SecurityConfig;
import com.medic.Web.config.auth.JwtAuthenticationConfig;
import com.medic.Web.config.mail.MailProperties;
import com.medic.Web.config.persistence.R2dbcConfig;
import com.medic.Web.config.persistence.UUIDAutoGeneratedConfig;
import com.medic.Web.config.properties.AnvisaEtlProperties;
import com.medic.Web.config.web.OpenAPIConfig;
import com.medic.Web.exception.handler.JwtEntryPoint;
import com.medic.Web.exception.handler.JwtAccessDenied;
import com.medic.Web.repository.usuario.UsuarioRepository;
import com.medic.Web.service.auth.JwtService;
import com.medic.Web.model.auth.RefreshTokenModel;
import org.junit.jupiter.api.Test;
import org.springframework.mock.web.server.MockServerWebExchange;
import org.springframework.security.access.hierarchicalroles.RoleHierarchy;
import org.springframework.security.config.web.server.ServerHttpSecurity;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.data.relational.core.sql.SqlIdentifier;
import reactor.core.publisher.Mono;
import reactor.test.StepVerifier;

import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.Mockito.mock;

class WebConfigurationCoverageTest {

    @Test
    void shouldExposeCorsConfiguration() {

        var source = new CorsConfig().corsConfigurationSource();
        var exchange = MockServerWebExchange.from(
                org.springframework.mock.http.server.reactive.MockServerHttpRequest.get("/").build()
        );
        var configuration = source.getCorsConfiguration(exchange);

        assertNotNull(configuration);
        assertEquals(java.util.List.of("GET", "POST", "PUT", "DELETE"), configuration.getAllowedMethods());
        assertEquals(java.util.List.of("*"), configuration.getAllowedHeaders());
    }

    @Test
    void shouldBuildSecurityBeans() {

        var security = new SecurityConfig(mock(JwtEntryPoint.class), mock(JwtAccessDenied.class));
        RoleHierarchy hierarchy = security.roleHierarchy();
        PasswordEncoder encoder = security.passwordEncoder();
        assertEquals("ROLE_USER", hierarchy.getReachableGrantedAuthorities(
                java.util.List.of(new org.springframework.security.core.authority.SimpleGrantedAuthority("ROLE_ADMIN"))
        ).stream().filter(authority -> authority.getAuthority().equals("ROLE_USER")).findFirst().orElseThrow().getAuthority());
        assertEquals("secret", encoder.matches("secret", encoder.encode("secret")) ? "secret" : "wrong");

        JwtAuthenticationConfig jwtConfig = new JwtAuthenticationConfig(
                mock(JwtService.class), mock(UsuarioRepository.class), mock(JwtEntryPoint.class)
        );
        assertNotNull(security.filterChain(
                jwtConfig,
                ServerHttpSecurity.http(),
                new CorsConfig().corsConfigurationSource(),
                hierarchy
        ));
    }

    @Test
    void shouldBuildOpenApiForDefaultAndHomologationProfiles() {

        OpenAPIConfig defaultConfig = new OpenAPIConfig();
        org.springframework.test.util.ReflectionTestUtils.setField(defaultConfig, "activeProfile", "dev");
        assertNotNull(defaultConfig.customOpenAPI().getComponents().getSecuritySchemes().get("BearerAuth"));
        assertEquals(null, defaultConfig.customOpenAPI().getServers());

        OpenAPIConfig hmlConfig = new OpenAPIConfig();
        org.springframework.test.util.ReflectionTestUtils.setField(hmlConfig, "activeProfile", "hml");
        assertEquals(1, hmlConfig.customOpenAPI().getServers().size());
    }

    @Test
    void shouldGenerateMissingUuidAndPreserveExistingUuid() {

        UUIDAutoGeneratedConfig callback = new UUIDAutoGeneratedConfig();
        RefreshTokenModel withoutId = new RefreshTokenModel();
        RefreshTokenModel withId = new RefreshTokenModel();
        UUID id = UUID.randomUUID();
        withId.setId(id);
        SqlIdentifier table = mock(SqlIdentifier.class);

        StepVerifier.create(Mono.from(callback.onBeforeConvert(withoutId, table)))
                .assertNext(entity -> assertNotNull(entity.getId()))
                .verifyComplete();
        StepVerifier.create(Mono.from(callback.onBeforeConvert(withId, table)))
                .assertNext(entity -> assertEquals(id, entity.getId()))
                .verifyComplete();
    }

    @Test
    void shouldInstantiateSimpleConfigurationTypes() {

        assertNotNull(new R2dbcConfig());
        assertEquals("user", new MailProperties("user").username());
        AnvisaEtlProperties properties = new AnvisaEtlProperties();
        properties.setBaseUrl("http://etl");
        properties.setApiKey("key");
        assertEquals("http://etl", properties.getBaseUrl());
        assertEquals("key", properties.getApiKey());
        assertNotNull(new com.medic.Web.config.persistence.UUIDAutoGeneratedConfig());
    }
}
