spring:
  application:
    name: produto-web-prod
  r2dbc:
    url: ${PRODUTO_WEB_PROD_URL}
    username: ${PRODUTO_WEB_PROD_USERNAME}
    password: ${PRODUTO_WEB_PROD_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 9092
  forward-headers-strategy: framework

logging:
  level:
    root: WARN

springdoc:
  swagger-ui:
    enabled: false
    path: /swagger-ui.html
  api-docs:
    enabled: false
    path: /api-docs
