spring:
  application:
    name: produto-etl-prod
  jpa:
    open-in-view: false

app:
  datasource:
    origem:
      ufx:
        driver-class-name: dbmaker.sql.type4.Driver
        url: ${DBMAKER_UFX_URL}
        username: ${DBMAKER_UFX_USERNAME}
        password: ${DBMAKER_UFX_PASSWORD}
      s00:
        driver-class-name: dbmaker.sql.type4.Driver
        url: ${DBMAKER_S00_URL}
        username: ${DBMAKER_S00_USERNAME}
        password: ${DBMAKER_S00_PASSWORD}
    produto:
      driver-class-name: org.postgresql.Driver
      url: ${PRODUTO_ETL_PROD_URL}
      username: ${PRODUTO_ETL_PROD_USERNAME}
      password: ${PRODUTO_ETL_PROD_PASSWORD}

etl:
  thread-pool-size: 4
