package com.medic.Web.model.auth;

import com.medic.Web.config.persistence.UUIDAutoGenerated;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

import java.io.Serial;
import java.io.Serializable;
import java.time.Instant;
import java.util.UUID;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "refresh_token")
public class RefreshTokenModel implements Serializable, UUIDAutoGenerated {

    @Serial
    private static final long serialVersionUID = 1L;

    @Id
    private UUID id;

    @Column("usuario_id")
    private UUID usuarioId;

    @Column("token_hash")
    private String tokenHash;

    @Column("family_id")
    private UUID familyId;

    @Column("expira_em")
    private Instant expiraEm;

    @Column("criado_em")
    private Instant criadoEm;

    @Column("revogado_em")
    private Instant revogadoEm;

    @Column("substituido_por")
    private UUID substituidoPor;

    @Column("ultimo_uso_em")
    private Instant ultimoUsoEm;

    public boolean isRevogado() {
        return revogadoEm != null;
    }
}
