package com.medic.Web.model.cd;

import com.medic.Web.config.persistence.UUIDAutoGenerated;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

import java.io.Serial;
import java.io.Serializable;
import java.time.Instant;
import java.util.UUID;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Table("cd_empresa_municipio")
public class CdEmpresaMunicipioModel implements Serializable, UUIDAutoGenerated {

    @Serial
    private static final long serialVersionUID = 1L;

    @Id
    private UUID id;

    @Column("id_cd")
    private UUID idCd;

    @Column("id_empresa_municipio")
    private UUID idEmpresaMunicipio;

    @Column("criado_por")
    private UUID criadoPor;

    @CreatedDate
    @Column("criado_em")
    private Instant criadoEm;
}
