package com.medic.Web.model.config.schedule;

import com.medic.Web.config.persistence.UUIDAutoGenerated;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

import java.io.Serial;
import java.io.Serializable;
import java.time.Instant;
import java.util.UUID;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Table("config_schedule")
public class ScheduleModel implements Serializable, UUIDAutoGenerated {

    @Serial
    private static final long serialVersionUID = 1L;

    @Id
    private UUID id;

    @Column
    private ScheduleJob job;

    @Column
    private String cron;

    @Column
    private boolean ativo;

    @Column
    private UUID atualizadoPor;

    @LastModifiedDate
    @Column
    private Instant atualizadoEm;

    @Column("ultima_execucao")
    private Instant ultimaExecucao;
}
